[package]
name = "brainstorm"
version = "0.1.0"
edition = "2018"
description = "Brainstorm is a web framework for Brainfuck"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
